export const GET_RESULTS = 'GET_RESULTS'
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS'
export const FETCH_IMAGE_ERROR = 'FETCH_IMAGE_ERROR'
export const FETCH_IMAGE_START = 'FETCH_IMAGE_START'
export const FETCH_LIKED_IMAGE = 'FETCH_LIKED_IMAGE'
export const IMAGE_TO_REMOVE = 'IMAGE_TO_REMOVE'

export const ADD_SEARCHED_TITLE = 'ADD_SEARCHED_TITLE'
export const REMOVE_SEARCHED_TITLE = 'REMOVE_SEARCHED_TITLE'
